version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/database_development
    depends_on:
      - db

    command: >
      sh -c "npm install &&
             npm run db:migrate &&
             npm test &&
             npm start"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_development
    ports:
      - "5432:5432"



